builders:
  # copyBuilder:
  #   import: "package:qs/builder.dart"
  #   builder_factories: ["copyBuilder"]
  #   build_extensions: {".txt": [".g.txt"]}
  #   build_to: source
  #   auto_apply: root_package

  # resolvingBuilder:
  #   import: "package:qs/builder.dart"
  #   builder_factories: ["resolvingBuilder"]
  #   build_extensions: {".dart": [".dart.info.json"]}
  #   build_to: source
  #   auto_apply: root_package
  #   defaults:
  #     generate_for:
  #       # Only apply to .dart files in the web directory
  #       include:
  #       - web/**